linters:
  enable-all: true
  disable:
    - nosnakecase
    - interfacer
    - deadcode
    - exhaustivestruct
    - ifshort
    - structcheck
    - golint
    - varcheck
    - maligned
    - scopelint
    - structcheck
    - gomnd
    - varnamelen
    - exhaustruct
    - gocognit
    - wrapcheck
    - nestif
    - cyclop
    - ireturn
    - bodyclose
    - godox
    - depguard
    - funlen
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  gosec:
    excludes:
      - G306
